#include "x86.hpp"

#include "../../utils/stringHelper.hpp"

std::vector<std::string> x86DefaultShownRegs = {"RIP", "RSP", "RBP", "RAX", "RBX", "RCX", "RDX", "RSI", "RDI", "R8", "R9", "R10", "R11", "R12", "R13", "R14", "R15",
    "CS", "DS", "ES", "FS", "GS", "SS"};

std::unordered_map<std::string, size_t> x86RegInfoMap = {
    {"invalid", {0}},
    {"ah", {8}}, {"al", {8}}, {"ax", {16}},
    {"bh", {8}}, {"bl", {8}}, {"bp", {16}}, {"bpl", {8}}, {"bx", {16}},
    {"ch", {8}}, {"cl", {8}}, {"cs", {16}}, {"cx", {16}},
    {"dh", {8}}, {"di", {16}}, {"dil", {8}}, {"dl", {8}}, {"ds", {16}}, {"dx", {16}},
    {"eax", {32}}, {"ebp", {32}}, {"ebx", {32}}, {"ecx", {32}}, {"edi", {32}}, {"edx", {32}},
    {"eflags", {32}}, {"eip", {32}}, {"es", {16}}, {"esi", {32}}, {"esp", {32}},
    {"fpsw", {16}}, {"fs", {16}}, {"gs", {16}}, {"ip", {16}},
    {"rax", {64}}, {"rbp", {64}}, {"rbx", {64}}, {"rcx", {64}}, {"rdi", {64}}, {"rdx", {64}},
    {"rip", {64}}, {"rsi", {64}}, {"rsp", {64}},
    {"si", {16}}, {"sil", {8}}, {"sp", {16}}, {"spl", {8}}, {"ss", {16}},
    {"cr0", {64}}, {"cr1", {64}}, {"cr2", {64}}, {"cr3", {64}}, {"cr4", {64}}, {"cr8", {64}},
    {"dr0", {64}}, {"dr1", {64}}, {"dr2", {64}}, {"dr3", {64}}, {"dr4", {64}}, {"dr5", {64}}, {"dr6", {64}}, {"dr7", {64}},
    {"fp0", {80}}, {"fp1", {80}}, {"fp2", {80}}, {"fp3", {80}}, {"fp4", {80}}, {"fp5", {80}}, {"fp6", {80}}, {"fp7", {80}},
    {"k0", {64}}, {"k1", {64}}, {"k2", {64}}, {"k3", {64}}, {"k4", {64}}, {"k5", {64}}, {"k6", {64}}, {"k7", {64}},
    {"mm0", {64}}, {"mm1", {64}}, {"mm2", {64}}, {"mm3", {64}}, {"mm4", {64}}, {"mm5", {64}}, {"mm6", {64}}, {"mm7", {64}},
    {"r8", {64}}, {"r9", {64}}, {"r10", {64}}, {"r11", {64}}, {"r12", {64}}, {"r13", {64}}, {"r14", {64}}, {"r15", {64}},
    {"st0", {80}}, {"st1", {80}}, {"st2", {80}}, {"st3", {80}}, {"st4", {80}}, {"st5", {80}}, {"st6", {80}}, {"st7", {80}},
    {"xmm0", {128}}, {"xmm1", {128}}, {"xmm2", {128}}, {"xmm3", {128}}, {"xmm4", {128}}, {"xmm5", {128}}, {"xmm6", {128}}, {"xmm7", {128}},
    {"xmm8", {128}}, {"xmm9", {128}}, {"xmm10", {128}}, {"xmm11", {128}}, {"xmm12", {128}}, {"xmm13", {128}}, {"xmm14", {128}}, {"xmm15", {128}},
    {"ymm0", {256}}, {"ymm1", {256}}, {"ymm2", {256}}, {"ymm3", {256}}, {"ymm4", {256}}, {"ymm5", {256}}, {"ymm6", {256}}, {"ymm7", {256}},
    {"ymm8", {256}}, {"ymm9", {256}}, {"ymm10", {256}}, {"ymm11", {256}}, {"ymm12", {256}}, {"ymm13", {256}}, {"ymm14", {256}}, {"ymm15", {256}},
    {"zmm0", {512}}, {"zmm1", {512}}, {"zmm2", {512}}, {"zmm3", {512}}, {"zmm4", {512}}, {"zmm5", {512}}, {"zmm6", {512}}, {"zmm7", {512}},
    {"zmm8", {512}}, {"zmm9", {512}}, {"zmm10", {512}}, {"zmm11", {512}}, {"zmm12", {512}}, {"zmm13", {512}}, {"zmm14", {512}}, {"zmm15", {512}},
    {"zmm16", {512}}, {"zmm17", {512}}, {"zmm18", {512}}, {"zmm19", {512}}, {"zmm20", {512}}, {"zmm21", {512}}, {"zmm22", {512}}, {"zmm23", {512}},
    {"zmm24", {512}}, {"zmm25", {512}}, {"zmm26", {512}}, {"zmm27", {512}}, {"zmm28", {512}}, {"zmm29", {512}}, {"zmm30", {512}}, {"zmm31", {512}},
    {"r8b", {8}}, {"r9b", {8}}, {"r10b", {8}}, {"r11b", {8}}, {"r12b", {8}}, {"r13b", {8}}, {"r14b", {8}}, {"r15b", {8}},
    {"r8d", {32}}, {"r9d", {32}}, {"r10d", {32}}, {"r11d", {32}}, {"r12d", {32}}, {"r13d", {32}}, {"r14d", {32}}, {"r15d", {32}},
    {"r8w", {16}}, {"r9w", {16}}, {"r10w", {16}}, {"r11w", {16}}, {"r12w", {16}}, {"r13w", {16}}, {"r14w", {16}}, {"r15w", {16}},
    {"idtr", {80}}, {"gdtr", {80}}, {"ldtr", {16}}, {"tr", {16}},
    {"fpcw", {16}}, {"fptag", {16}}, {"msr", {64}}, {"mxcsr", {32}},
    {"fs_base", {64}}, {"gs_base", {64}},
    {"flags", {32}}, {"rflags", {64}},
    {"fip", {64}}, {"fcs", {16}}, {"fdp", {64}}, {"fds", {16}}, {"fop", {16}}
};

std::vector<std::string> x86ArchInstructions = {"AAA", "AAD", "AAM", "AAS", "FABS", "ADC", "ADCX", "ADD", "ADDPD", "ADDPS", "ADDSD", "ADDSS", "ADDSUBPD", "ADDSUBPS", "FADD", "FIADD", "ADOX", "AESDECLAST", "AESDEC", "AESENCLAST", "AESENC", "AESIMC", "AESKEYGENASSIST", "AND", "ANDN", "ANDNPD", "ANDNPS", "ANDPD", "ANDPS", "ARPL", "BEXTR", "BLCFILL", "BLCI", "BLCIC", "BLCMSK", "BLCS", "BLENDPD", "BLENDPS", "BLENDVPD", "BLENDVPS", "BLSFILL", "BLSI", "BLSIC", "BLSMSK", "BLSR", "BNDCL", "BNDCN", "BNDCU", "BNDLDX", "BNDMK", "BNDMOV", "BNDSTX", "BOUND", "BSF", "BSR", "BSWAP", "BT", "BTC", "BTR", "BTS", "BZHI", "CALL", "CBW", "CDQ", "CDQE", "FCHS", "CLAC", "CLC", "CLD", "CLDEMOTE", "CLFLUSH", "CLFLUSHOPT", "CLGI", "CLI", "CLRSSBSY", "CLTS", "CLWB", "CLZERO", "CMC", "CMOVA", "CMOVAE", "CMOVB", "CMOVBE", "FCMOVBE", "FCMOVB", "CMOVE", "FCMOVE", "CMOVG", "CMOVGE", "CMOVL", "CMOVLE", "FCMOVNBE", "FCMOVNB", "CMOVNE", "FCMOVNE", "CMOVNO", "CMOVNP", "FCMOVNU", "FCMOVNP", "CMOVNS", "CMOVO", "CMOVP", "FCMOVU", "CMOVS", "CMP", "CMPPD", "CMPPS", "CMPSB", "CMPSD", "CMPSQ", "CMPSS", "CMPSW", "CMPXCHG16B", "CMPXCHG", "CMPXCHG8B", "COMISD", "COMISS", "FCOMP", "FCOMPI", "FCOMI", "FCOM", "FCOS", "CPUID", "CQO", "CRC32", "CVTDQ2PD", "CVTDQ2PS", "CVTPD2DQ", "CVTPD2PS", "CVTPS2DQ", "CVTPS2PD", "CVTSD2SI", "CVTSD2SS", "CVTSI2SD", "CVTSI2SS", "CVTSS2SD", "CVTSS2SI", "CVTTPD2DQ", "CVTTPS2DQ", "CVTTSD2SI", "CVTTSS2SI", "CWD", "CWDE", "DAA", "DAS", "DATA16", "DEC", "DIV", "DIVPD", "DIVPS", "FDIVR", "FIDIVR", "FDIVRP", "DIVSD", "DIVSS", "FDIV", "FIDIV", "FDIVP", "DPPD", "DPPS", "ENCLS", "ENCLU", "ENCLV", "ENDBR32", "ENDBR64", "ENTER", "EXTRACTPS", "EXTRQ", "F2XM1", "LCALL", "LJMP", "JMP", "FBLD", "FBSTP", "FCOMPP", "FDECSTP", "FDISI8087_NOP", "FEMMS", "FENI8087_NOP", "FFREE", "FFREEP", "FICOM", "FICOMP", "FINCSTP", "FLDCW", "FLDENV", "FLDL2E", "FLDL2T", "FLDLG2", "FLDLN2", "FLDPI", "FNCLEX", "FNINIT", "FNOP", "FNSTCW", "FNSTSW", "FPATAN", "FSTPNCE", "FPREM", "FPREM1", "FPTAN", "FRNDINT", "FRSTOR", "FNSAVE", "FSCALE", "FSETPM", "FSINCOS", "FNSTENV", "FXAM", "FXRSTOR", "FXRSTOR64", "FXSAVE", "FXSAVE64", "FXTRACT", "FYL2X", "FYL2XP1", "GETSEC", "GF2P8AFFINEINVQB", "GF2P8AFFINEQB", "GF2P8MULB", "HADDPD", "HADDPS", "HLT", "HSUBPD", "HSUBPS", "IDIV", "FILD", "IMUL", "IN", "INC", "INCSSPD", "INCSSPQ", "INSB", "INSERTPS", "INSERTQ", "INSD", "INSW", "INT", "INT1", "INT3", "INTO", "INVD", "INVEPT", "INVLPG", "INVLPGA", "INVPCID", "INVVPID", "IRET", "IRETD", "IRETQ", "FISTTP", "FIST", "FISTP", "JAE", "JA", "JBE", "JB", "JCXZ", "JECXZ", "JE", "JGE", "JG", "JLE", "JL", "JNE", "JNO", "JNP", "JNS", "JO", "JP", "JRCXZ", "JS", "KADDB", "KADDD", "KADDQ", "KADDW", "KANDB", "KANDD", "KANDNB", "KANDND", "KANDNQ", "KANDNW", "KANDQ", "KANDW", "KMOVB", "KMOVD", "KMOVQ", "KMOVW", "KNOTB", "KNOTD", "KNOTQ", "KNOTW", "KORB", "KORD", "KORQ", "KORTESTB", "KORTESTD", "KORTESTQ", "KORTESTW", "KORW", "KSHIFTLB", "KSHIFTLD", "KSHIFTLQ", "KSHIFTLW", "KSHIFTRB", "KSHIFTRD", "KSHIFTRQ", "KSHIFTRW", "KTESTB", "KTESTD", "KTESTQ", "KTESTW", "KUNPCKBW", "KUNPCKDQ", "KUNPCKWD", "KXNORB", "KXNORD", "KXNORQ", "KXNORW", "KXORB", "KXORD", "KXORQ", "KXORW", "LAHF", "LAR", "LDDQU", "LDMXCSR", "LDS", "FLDZ", "FLD1", "FLD", "LEA", "LEAVE", "LES", "LFENCE", "LFS", "LGDT", "LGS", "LIDT", "LLDT", "LLWPCB", "LMSW", "LOCK", "LODSB", "LODSD", "LODSQ", "LODSW", "LOOP", "LOOPE", "LOOPNE", "RETF", "RETFQ", "LSL", "LSS", "LTR", "LWPINS", "LWPVAL", "LZCNT", "MASKMOVDQU", "MAXPD", "MAXPS", "MAXSD", "MAXSS", "MFENCE", "MINPD", "MINPS", "MINSD", "MINSS", "CVTPD2PI", "CVTPI2PD", "CVTPI2PS", "CVTPS2PI", "CVTTPD2PI", "CVTTPS2PI", "EMMS", "MASKMOVQ", "MOVD", "MOVQ", "MOVDQ2Q", "MOVNTQ", "MOVQ2DQ", "PABSB", "PABSD", "PABSW", "PACKSSDW", "PACKSSWB", "PACKUSWB", "PADDB", "PADDD", "PADDQ", "PADDSB", "PADDSW", "PADDUSB", "PADDUSW", "PADDW", "PALIGNR", "PANDN", "PAND", "PAVGB", "PAVGW", "PCMPEQB", "PCMPEQD", "PCMPEQW", "PCMPGTB", "PCMPGTD", "PCMPGTW", "PEXTRW", "PHADDD", "PHADDSW", "PHADDW", "PHSUBD", "PHSUBSW", "PHSUBW", "PINSRW", "PMADDUBSW", "PMADDWD", "PMAXSW", "PMAXUB", "PMINSW", "PMINUB", "PMOVMSKB", "PMULHRSW", "PMULHUW", "PMULHW", "PMULLW", "PMULUDQ", "POR", "PSADBW", "PSHUFB", "PSHUFW", "PSIGNB", "PSIGND", "PSIGNW", "PSLLD", "PSLLQ", "PSLLW", "PSRAD", "PSRAW", "PSRLD", "PSRLQ", "PSRLW", "PSUBB", "PSUBD", "PSUBQ", "PSUBSB", "PSUBSW", "PSUBUSB", "PSUBUSW", "PSUBW", "PUNPCKHBW", "PUNPCKHDQ", "PUNPCKHWD", "PUNPCKLBW", "PUNPCKLDQ", "PUNPCKLWD", "PXOR", "MONITORX", "MONITOR", "MONTMUL", "MOV", "MOVABS", "MOVAPD", "MOVAPS", "MOVBE", "MOVDDUP", "MOVDIR64B", "MOVDIRI", "MOVDQA", "MOVDQU", "MOVHLPS", "MOVHPD", "MOVHPS", "MOVLHPS", "MOVLPD", "MOVLPS", "MOVMSKPD", "MOVMSKPS", "MOVNTDQA", "MOVNTDQ", "MOVNTI", "MOVNTPD", "MOVNTPS", "MOVNTSD", "MOVNTSS", "MOVSB", "MOVSD", "MOVSHDUP", "MOVSLDUP", "MOVSQ", "MOVSS", "MOVSW", "MOVSX", "MOVSXD", "MOVUPD", "MOVUPS", "MOVZX", "MPSADBW", "MUL", "MULPD", "MULPS", "MULSD", "MULSS", "MULX", "FMUL", "FIMUL", "FMULP", "MWAITX", "MWAIT", "NEG", "NOP", "NOT", "OR", "ORPD", "ORPS", "OUT", "OUTSB", "OUTSD", "OUTSW", "PACKUSDW", "PAUSE", "PAVGUSB", "PBLENDVB", "PBLENDW", "PCLMULQDQ", "PCMPEQQ", "PCMPESTRI", "PCMPESTRM", "PCMPGTQ", "PCMPISTRI", "PCMPISTRM", "PCONFIG", "PDEP", "PEXT", "PEXTRB", "PEXTRD", "PEXTRQ", "PF2ID", "PF2IW", "PFACC", "PFADD", "PFCMPEQ", "PFCMPGE", "PFCMPGT", "PFMAX", "PFMIN", "PFMUL", "PFNACC", "PFPNACC", "PFRCPIT1", "PFRCPIT2", "PFRCP", "PFRSQIT1", "PFRSQRT", "PFSUBR", "PFSUB", "PHMINPOSUW", "PI2FD", "PI2FW", "PINSRB", "PINSRD", "PINSRQ", "PMAXSB", "PMAXSD", "PMAXUD", "PMAXUW", "PMINSB", "PMINSD", "PMINUD", "PMINUW", "PMOVSXBD", "PMOVSXBQ", "PMOVSXBW", "PMOVSXDQ", "PMOVSXWD", "PMOVSXWQ", "PMOVZXBD", "PMOVZXBQ", "PMOVZXBW", "PMOVZXDQ", "PMOVZXWD", "PMOVZXWQ", "PMULDQ", "PMULHRW", "PMULLD", "POP", "POPAW", "POPAL", "POPCNT", "POPF", "POPFD", "POPFQ", "PREFETCH", "PREFETCHNTA", "PREFETCHT0", "PREFETCHT1", "PREFETCHT2", "PREFETCHW", "PREFETCHWT1", "PSHUFD", "PSHUFHW", "PSHUFLW", "PSLLDQ", "PSRLDQ", "PSWAPD", "PTEST", "PTWRITE", "PUNPCKHQDQ", "PUNPCKLQDQ", "PUSH", "PUSHAW", "PUSHAL", "PUSHF", "PUSHFD", "PUSHFQ", "RCL", "RCPPS", "RCPSS", "RCR", "RDFSBASE", "RDGSBASE", "RDMSR", "RDPID", "RDPKRU", "RDPMC", "RDRAND", "RDSEED", "RDSSPD", "RDSSPQ", "RDTSC", "RDTSCP", "REPNE", "REP", "RET", "REX64", "ROL", "ROR", "RORX", "ROUNDPD", "ROUNDPS", "ROUNDSD", "ROUNDSS", "RSM", "RSQRTPS", "RSQRTSS", "RSTORSSP", "SAHF", "SAL", "SALC", "SAR", "SARX", "SAVEPREVSSP", "SBB", "SCASB", "SCASD", "SCASQ", "SCASW", "SETAE", "SETA", "SETBE", "SETB", "SETE", "SETGE", "SETG", "SETLE", "SETL", "SETNE", "SETNO", "SETNP", "SETNS", "SETO", "SETP", "SETSSBSY", "SETS", "SFENCE", "SGDT", "SHA1MSG1", "SHA1MSG2", "SHA1NEXTE", "SHA1RNDS4", "SHA256MSG1", "SHA256MSG2", "SHA256RNDS2", "SHL", "SHLD", "SHLX", "SHR", "SHRD", "SHRX", "SHUFPD", "SHUFPS", "SIDT", "FSIN", "SKINIT", "SLDT", "SLWPCB", "SMSW", "SQRTPD", "SQRTPS", "SQRTSD", "SQRTSS", "FSQRT", "STAC", "STC", "STD", "STGI", "STI", "STMXCSR", "STOSB", "STOSD", "STOSQ", "STOSW", "STR", "FST", "FSTP", "SUB", "SUBPD", "SUBPS", "FSUBR", "FISUBR", "FSUBRP", "SUBSD", "SUBSS", "FSUB", "FISUB", "FSUBP", "SWAPGS", "SYSCALL", "SYSENTER", "SYSEXIT", "SYSEXITQ", "SYSRET", "SYSRETQ", "T1MSKC", "TEST", "TPAUSE", "FTST", "TZCNT", "TZMSK", "UCOMISD", "UCOMISS", "FUCOMPI", "FUCOMI", "FUCOMPP", "FUCOMP", "FUCOM", "UD0", "UD1", "UD2", "UMONITOR", "UMWAIT", "UNPCKHPD", "UNPCKHPS", "UNPCKLPD", "UNPCKLPS", "V4FMADDPS", "V4FMADDSS", "V4FNMADDPS", "V4FNMADDSS", "VADDPD", "VADDPS", "VADDSD", "VADDSS", "VADDSUBPD", "VADDSUBPS", "VAESDECLAST", "VAESDEC", "VAESENCLAST", "VAESENC", "VAESIMC", "VAESKEYGENASSIST", "VALIGND", "VALIGNQ", "VANDNPD", "VANDNPS", "VANDPD", "VANDPS", "VBLENDMPD", "VBLENDMPS", "VBLENDPD", "VBLENDPS", "VBLENDVPD", "VBLENDVPS", "VBROADCASTF128", "VBROADCASTF32X2", "VBROADCASTF32X4", "VBROADCASTF32X8", "VBROADCASTF64X2", "VBROADCASTF64X4", "VBROADCASTI128", "VBROADCASTI32X2", "VBROADCASTI32X4", "VBROADCASTI32X8", "VBROADCASTI64X2", "VBROADCASTI64X4", "VBROADCASTSD", "VBROADCASTSS", "VCMP", "VCMPPD", "VCMPPS", "VCMPSD", "VCMPSS", "VCOMISD", "VCOMISS", "VCOMPRESSPD", "VCOMPRESSPS", "VCVTDQ2PD", "VCVTDQ2PS", "VCVTPD2DQ", "VCVTPD2PS", "VCVTPD2QQ", "VCVTPD2UDQ", "VCVTPD2UQQ", "VCVTPH2PS", "VCVTPS2DQ", "VCVTPS2PD", "VCVTPS2PH", "VCVTPS2QQ", "VCVTPS2UDQ", "VCVTPS2UQQ", "VCVTQQ2PD", "VCVTQQ2PS", "VCVTSD2SI", "VCVTSD2SS", "VCVTSD2USI", "VCVTSI2SD", "VCVTSI2SS", "VCVTSS2SD", "VCVTSS2SI", "VCVTSS2USI", "VCVTTPD2DQ", "VCVTTPD2QQ", "VCVTTPD2UDQ", "VCVTTPD2UQQ", "VCVTTPS2DQ", "VCVTTPS2QQ", "VCVTTPS2UDQ", "VCVTTPS2UQQ", "VCVTTSD2SI", "VCVTTSD2USI", "VCVTTSS2SI", "VCVTTSS2USI", "VCVTUDQ2PD", "VCVTUDQ2PS", "VCVTUQQ2PD", "VCVTUQQ2PS", "VCVTUSI2SD", "VCVTUSI2SS", "VDBPSADBW", "VDIVPD", "VDIVPS", "VDIVSD", "VDIVSS", "VDPPD", "VDPPS", "VERR", "VERW", "VEXP2PD", "VEXP2PS", "VEXPANDPD", "VEXPANDPS", "VEXTRACTF128", "VEXTRACTF32X4", "VEXTRACTF32X8", "VEXTRACTF64X2", "VEXTRACTF64X4", "VEXTRACTI128", "VEXTRACTI32X4", "VEXTRACTI32X8", "VEXTRACTI64X2", "VEXTRACTI64X4", "VEXTRACTPS", "VFIXUPIMMPD", "VFIXUPIMMPS", "VFIXUPIMMSD", "VFIXUPIMMSS", "VFMADD132PD", "VFMADD132PS", "VFMADD132SD", "VFMADD132SS", "VFMADD213PD", "VFMADD213PS", "VFMADD213SD", "VFMADD213SS", "VFMADD231PD", "VFMADD231PS", "VFMADD231SD", "VFMADD231SS", "VFMADDPD", "VFMADDPS", "VFMADDSD", "VFMADDSS", "VFMADDSUB132PD", "VFMADDSUB132PS", "VFMADDSUB213PD", "VFMADDSUB213PS", "VFMADDSUB231PD", "VFMADDSUB231PS", "VFMADDSUBPD", "VFMADDSUBPS", "VFMSUB132PD", "VFMSUB132PS", "VFMSUB132SD", "VFMSUB132SS", "VFMSUB213PD", "VFMSUB213PS", "VFMSUB213SD", "VFMSUB213SS", "VFMSUB231PD", "VFMSUB231PS", "VFMSUB231SD", "VFMSUB231SS", "VFMSUBADD132PD", "VFMSUBADD132PS", "VFMSUBADD213PD", "VFMSUBADD213PS", "VFMSUBADD231PD", "VFMSUBADD231PS", "VFMSUBADDPD", "VFMSUBADDPS", "VFMSUBPD", "VFMSUBPS", "VFMSUBSD", "VFMSUBSS", "VFNMADD132PD", "VFNMADD132PS", "VFNMADD132SD", "VFNMADD132SS", "VFNMADD213PD", "VFNMADD213PS", "VFNMADD213SD", "VFNMADD213SS", "VFNMADD231PD", "VFNMADD231PS", "VFNMADD231SD", "VFNMADD231SS", "VFNMADDPD", "VFNMADDPS", "VFNMADDSD", "VFNMADDSS", "VFNMSUB132PD", "VFNMSUB132PS", "VFNMSUB132SD", "VFNMSUB132SS", "VFNMSUB213PD", "VFNMSUB213PS", "VFNMSUB213SD", "VFNMSUB213SS", "VFNMSUB231PD", "VFNMSUB231PS", "VFNMSUB231SD", "VFNMSUB231SS", "VFNMSUBPD", "VFNMSUBPS", "VFNMSUBSD", "VFNMSUBSS", "VFPCLASSPD", "VFPCLASSPS", "VFPCLASSSD", "VFPCLASSSS", "VFRCZPD", "VFRCZPS", "VFRCZSD", "VFRCZSS", "VGATHERDPD", "VGATHERDPS", "VGATHERPF0DPD", "VGATHERPF0DPS", "VGATHERPF0QPD", "VGATHERPF0QPS", "VGATHERPF1DPD", "VGATHERPF1DPS", "VGATHERPF1QPD", "VGATHERPF1QPS", "VGATHERQPD", "VGATHERQPS", "VGETEXPPD", "VGETEXPPS", "VGETEXPSD", "VGETEXPSS", "VGETMANTPD", "VGETMANTPS", "VGETMANTSD", "VGETMANTSS", "VGF2P8AFFINEINVQB", "VGF2P8AFFINEQB", "VGF2P8MULB", "VHADDPD", "VHADDPS", "VHSUBPD", "VHSUBPS", "VINSERTF128", "VINSERTF32X4", "VINSERTF32X8", "VINSERTF64X2", "VINSERTF64X4", "VINSERTI128", "VINSERTI32X4", "VINSERTI32X8", "VINSERTI64X2", "VINSERTI64X4", "VINSERTPS", "VLDDQU", "VLDMXCSR", "VMASKMOVDQU", "VMASKMOVPD", "VMASKMOVPS", "VMAXPD", "VMAXPS", "VMAXSD", "VMAXSS", "VMCALL", "VMCLEAR", "VMFUNC", "VMINPD", "VMINPS", "VMINSD", "VMINSS", "VMLAUNCH", "VMLOAD", "VMMCALL", "VMOVQ", "VMOVAPD", "VMOVAPS", "VMOVDDUP", "VMOVD", "VMOVDQA32", "VMOVDQA64", "VMOVDQA", "VMOVDQU16", "VMOVDQU32", "VMOVDQU64", "VMOVDQU8", "VMOVDQU", "VMOVHLPS", "VMOVHPD", "VMOVHPS", "VMOVLHPS", "VMOVLPD", "VMOVLPS", "VMOVMSKPD", "VMOVMSKPS", "VMOVNTDQA", "VMOVNTDQ", "VMOVNTPD", "VMOVNTPS", "VMOVSD", "VMOVSHDUP", "VMOVSLDUP", "VMOVSS", "VMOVUPD", "VMOVUPS", "VMPSADBW", "VMPTRLD", "VMPTRST", "VMREAD", "VMRESUME", "VMRUN", "VMSAVE", "VMULPD", "VMULPS", "VMULSD", "VMULSS", "VMWRITE", "VMXOFF", "VMXON", "VORPD", "VORPS", "VP4DPWSSDS", "VP4DPWSSD", "VPABSB", "VPABSD", "VPABSQ", "VPABSW", "VPACKSSDW", "VPACKSSWB", "VPACKUSDW", "VPACKUSWB", "VPADDB", "VPADDD", "VPADDQ", "VPADDSB", "VPADDSW", "VPADDUSB", "VPADDUSW", "VPADDW", "VPALIGNR", "VPANDD", "VPANDND", "VPANDNQ", "VPANDN", "VPANDQ", "VPAND", "VPAVGB", "VPAVGW", "VPBLENDD", "VPBLENDMB", "VPBLENDMD", "VPBLENDMQ", "VPBLENDMW", "VPBLENDVB", "VPBLENDW", "VPBROADCASTB", "VPBROADCASTD", "VPBROADCASTMB2Q", "VPBROADCASTMW2D", "VPBROADCASTQ", "VPBROADCASTW", "VPCLMULQDQ", "VPCMOV", "VPCMP", "VPCMPB", "VPCMPD", "VPCMPEQB", "VPCMPEQD", "VPCMPEQQ", "VPCMPEQW", "VPCMPESTRI", "VPCMPESTRM", "VPCMPGTB", "VPCMPGTD", "VPCMPGTQ", "VPCMPGTW", "VPCMPISTRI", "VPCMPISTRM", "VPCMPQ", "VPCMPUB", "VPCMPUD", "VPCMPUQ", "VPCMPUW", "VPCMPW", "VPCOM", "VPCOMB", "VPCOMD", "VPCOMPRESSB", "VPCOMPRESSD", "VPCOMPRESSQ", "VPCOMPRESSW", "VPCOMQ", "VPCOMUB", "VPCOMUD", "VPCOMUQ", "VPCOMUW", "VPCOMW", "VPCONFLICTD", "VPCONFLICTQ", "VPDPBUSDS", "VPDPBUSD", "VPDPWSSDS", "VPDPWSSD", "VPERM2F128", "VPERM2I128", "VPERMB", "VPERMD", "VPERMI2B", "VPERMI2D", "VPERMI2PD", "VPERMI2PS", "VPERMI2Q", "VPERMI2W", "VPERMIL2PD", "VPERMILPD", "VPERMIL2PS", "VPERMILPS", "VPERMPD", "VPERMPS", "VPERMQ", "VPERMT2B", "VPERMT2D", "VPERMT2PD", "VPERMT2PS", "VPERMT2Q", "VPERMT2W", "VPERMW", "VPEXPANDB", "VPEXPANDD", "VPEXPANDQ", "VPEXPANDW", "VPEXTRB", "VPEXTRD", "VPEXTRQ", "VPEXTRW", "VPGATHERDD", "VPGATHERDQ", "VPGATHERQD", "VPGATHERQQ", "VPHADDBD", "VPHADDBQ", "VPHADDBW", "VPHADDDQ", "VPHADDD", "VPHADDSW", "VPHADDUBD", "VPHADDUBQ", "VPHADDUBW", "VPHADDUDQ", "VPHADDUWD", "VPHADDUWQ", "VPHADDWD", "VPHADDWQ", "VPHADDW", "VPHMINPOSUW", "VPHSUBBW", "VPHSUBDQ", "VPHSUBD", "VPHSUBSW", "VPHSUBWD", "VPHSUBW", "VPINSRB", "VPINSRD", "VPINSRQ", "VPINSRW", "VPLZCNTD", "VPLZCNTQ", "VPMACSDD", "VPMACSDQH", "VPMACSDQL", "VPMACSSDD", "VPMACSSDQH", "VPMACSSDQL", "VPMACSSWD", "VPMACSSWW", "VPMACSWD", "VPMACSWW", "VPMADCSSWD", "VPMADCSWD", "VPMADD52HUQ", "VPMADD52LUQ", "VPMADDUBSW", "VPMADDWD", "VPMASKMOVD", "VPMASKMOVQ", "VPMAXSB", "VPMAXSD", "VPMAXSQ", "VPMAXSW", "VPMAXUB", "VPMAXUD", "VPMAXUQ", "VPMAXUW", "VPMINSB", "VPMINSD", "VPMINSQ", "VPMINSW", "VPMINUB", "VPMINUD", "VPMINUQ", "VPMINUW", "VPMOVB2M", "VPMOVD2M", "VPMOVDB", "VPMOVDW", "VPMOVM2B", "VPMOVM2D", "VPMOVM2Q", "VPMOVM2W", "VPMOVMSKB", "VPMOVQ2M", "VPMOVQB", "VPMOVQD", "VPMOVQW", "VPMOVSDB", "VPMOVSDW", "VPMOVSQB", "VPMOVSQD", "VPMOVSQW", "VPMOVSWB", "VPMOVSXBD", "VPMOVSXBQ", "VPMOVSXBW", "VPMOVSXDQ", "VPMOVSXWD", "VPMOVSXWQ", "VPMOVUSDB", "VPMOVUSDW", "VPMOVUSQB", "VPMOVUSQD", "VPMOVUSQW", "VPMOVUSWB", "VPMOVW2M", "VPMOVWB", "VPMOVZXBD", "VPMOVZXBQ", "VPMOVZXBW", "VPMOVZXDQ", "VPMOVZXWD", "VPMOVZXWQ", "VPMULDQ", "VPMULHRSW", "VPMULHUW", "VPMULHW", "VPMULLD", "VPMULLQ", "VPMULLW", "VPMULTISHIFTQB", "VPMULUDQ", "VPOPCNTB", "VPOPCNTD", "VPOPCNTQ", "VPOPCNTW", "VPORD", "VPORQ", "VPOR", "VPPERM", "VPROLD", "VPROLQ", "VPROLVD", "VPROLVQ", "VPRORD", "VPRORQ", "VPRORVD", "VPRORVQ", "VPROTB", "VPROTD", "VPROTQ", "VPROTW", "VPSADBW", "VPSCATTERDD", "VPSCATTERDQ", "VPSCATTERQD", "VPSCATTERQQ", "VPSHAB", "VPSHAD", "VPSHAQ", "VPSHAW", "VPSHLB", "VPSHLDD", "VPSHLDQ", "VPSHLDVD", "VPSHLDVQ", "VPSHLDVW", "VPSHLDW", "VPSHLD", "VPSHLQ", "VPSHLW", "VPSHRDD", "VPSHRDQ", "VPSHRDVD", "VPSHRDVQ", "VPSHRDVW", "VPSHRDW", "VPSHUFBITQMB", "VPSHUFB", "VPSHUFD", "VPSHUFHW", "VPSHUFLW", "VPSIGNB", "VPSIGND", "VPSIGNW", "VPSLLDQ", "VPSLLD", "VPSLLQ", "VPSLLVD", "VPSLLVQ", "VPSLLVW", "VPSLLW", "VPSRAD", "VPSRAQ", "VPSRAVD", "VPSRAVQ", "VPSRAVW", "VPSRAW", "VPSRLDQ", "VPSRLD", "VPSRLQ", "VPSRLVD", "VPSRLVQ", "VPSRLVW", "VPSRLW", "VPSUBB", "VPSUBD", "VPSUBQ", "VPSUBSB", "VPSUBSW", "VPSUBUSB", "VPSUBUSW", "VPSUBW", "VPTERNLOGD", "VPTERNLOGQ", "VPTESTMB", "VPTESTMD", "VPTESTMQ", "VPTESTMW", "VPTESTNMB", "VPTESTNMD", "VPTESTNMQ", "VPTESTNMW", "VPTEST", "VPUNPCKHBW", "VPUNPCKHDQ", "VPUNPCKHQDQ", "VPUNPCKHWD", "VPUNPCKLBW", "VPUNPCKLDQ", "VPUNPCKLQDQ", "VPUNPCKLWD", "VPXORD", "VPXORQ", "VPXOR", "VRANGEPD", "VRANGEPS", "VRANGESD", "VRANGESS", "VRCP14PD", "VRCP14PS", "VRCP14SD", "VRCP14SS", "VRCP28PD", "VRCP28PS", "VRCP28SD", "VRCP28SS", "VRCPPS", "VRCPSS", "VREDUCEPD", "VREDUCEPS", "VREDUCESD", "VREDUCESS", "VRNDSCALEPD", "VRNDSCALEPS", "VRNDSCALESD", "VRNDSCALESS", "VROUNDPD", "VROUNDPS", "VROUNDSD", "VROUNDSS", "VRSQRT14PD", "VRSQRT14PS", "VRSQRT14SD", "VRSQRT14SS", "VRSQRT28PD", "VRSQRT28PS", "VRSQRT28SD", "VRSQRT28SS", "VRSQRTPS", "VRSQRTSS", "VSCALEFPD", "VSCALEFPS", "VSCALEFSD", "VSCALEFSS", "VSCATTERDPD", "VSCATTERDPS", "VSCATTERPF0DPD", "VSCATTERPF0DPS", "VSCATTERPF0QPD", "VSCATTERPF0QPS", "VSCATTERPF1DPD", "VSCATTERPF1DPS", "VSCATTERPF1QPD", "VSCATTERPF1QPS", "VSCATTERQPD", "VSCATTERQPS", "VSHUFF32X4", "VSHUFF64X2", "VSHUFI32X4", "VSHUFI64X2", "VSHUFPD", "VSHUFPS", "VSQRTPD", "VSQRTPS", "VSQRTSD", "VSQRTSS", "VSTMXCSR", "VSUBPD", "VSUBPS", "VSUBSD", "VSUBSS", "VTESTPD", "VTESTPS", "VUCOMISD", "VUCOMISS", "VUNPCKHPD", "VUNPCKHPS", "VUNPCKLPD", "VUNPCKLPS", "VXORPD", "VXORPS", "VZEROALL", "VZEROUPPER", "WAIT", "WBINVD", "WBNOINVD", "WRFSBASE", "WRGSBASE", "WRMSR", "WRPKRU", "WRSSD", "WRSSQ", "WRUSSD", "WRUSSQ", "XABORT", "XACQUIRE", "XADD", "XBEGIN", "XCHG", "FXCH", "XCRYPTCBC", "XCRYPTCFB", "XCRYPTCTR", "XCRYPTECB", "XCRYPTOFB", "XEND", "XGETBV", "XLATB", "XOR", "XORPD", "XORPS", "XRELEASE", "XRSTOR", "XRSTOR64", "XRSTORS", "XRSTORS64", "XSAVE", "XSAVE64", "XSAVEC", "XSAVEC64", "XSAVEOPT", "XSAVEOPT64", "XSAVES", "XSAVES64", "XSETBV", "XSHA1", "XSHA256", "XSTORE", "XTEST"};

std::string x86IPStr(const uc_mode mode){
    switch (mode) {
        case UC_MODE_16:
            return "IP";
        case UC_MODE_32:
            return "EIP";
        case UC_MODE_64:
            return "RIP";
        default:
            return "";
    }
}

std::pair<std::string, std::string> x86SBPStr(const uc_mode mode){
    switch (mode) {
        case UC_MODE_16:
            return {"SP", "BP"};
        case UC_MODE_32:
            return {"ESP", "EBP"};
        case UC_MODE_64:
            return {"RSP", "RBP"};
        default:
            return {"", ""};
    }
}

bool x86IsRegisterValid(const std::string& reg){
    std::string registerName = reg;
    if (registerName.contains("[") && registerName.contains(":") && registerName.contains("]")){
        registerName = registerName.substr(0, registerName.find_first_of('['));
    }

    if (!x86RegInfoMap.contains(toLowerCase(registerName))){
        return false;
    }


    if (!registerName.contains("ST") || (!registerName.contains("MM") || (!registerName.contains("XMM")) ||
        (!registerName.contains("YMM")) || (!registerName.contains("ZMM"))))
    {
        if ((registerName.starts_with("XMM") || registerName.starts_with("YMM")) && registerName.length() > 3) {
            const int suffix = atoi(registerName.substr(3).c_str());
            if (suffix > 15) {
                return false;
            }
        }
        else if (registerName.starts_with("ZMM")) {
            const int suffix = atoi(registerName.substr(3).c_str());
            if (suffix > 31) {
                return false;
            }
        }
    }

    if (x86RegInfoMap[registerName] == 64){
        return true;
    }
    if (x86RegInfoMap[registerName] == 128){
        return true;
    }

    return true;
}

void x86ModeUpdateCallback(){
    return;
    // switch (mode) {
    //     case UC_MODE_16:
    //         x86DefaultShownRegs = x86DefaultShownRegs16;
    //         break;
    //     case UC_MODE_32:
    //         x86DefaultShownRegs = x86DefaultShownRegs32;
    //         break;
    //     case UC_MODE_64:
    //         x86DefaultShownRegs = x86DefaultShownRegs64;
    //         break;
    //     default: ;
    // }
}